---
home_stack_app_dir: /opt/home-stack
home_stack_compose_file: docker/compose.yml
home_stack_env_file: /home/{{ home_stack_deploy_user }}/home-stack.env
home_stack_release_file: /home/{{ home_stack_deploy_user }}/home-stack.release
home_stack_source_mode: git
home_stack_git_repo: ''
home_stack_git_version: main
home_stack_deploy_user: deploy
home_stack_deploy_group: '{{ home_stack_deploy_user }}'
home_stack_hide_secrets: true
home_stack_run_health_checks: true
home_stack_health_check_url: '{{ home_stack_public_api_origin }}/health'
home_stack_health_check_validate_certs: true
