services:
  watchtower:
    image: nickfedor/watchtower:1.18.1
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    environment:
      WATCHTOWER_TRIGGERED_BY: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_HTTP_API: "true"
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_API_TOKEN}
      WATCHTOWER_HTTP_API_PERIODIC_POLLS: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - edge